spring:
  application:
    name: task-time-traker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/task_tracker
    username: root
    password: root

  liquibase:
    change-log: classpath:/db/changelog/db.migrations-master.yaml
    enabled: true


mybatis:
  type-aliases-package: com.veteroch4k.tasktracker.models


server:
  port: 8080
logging:
  level:
    root: info
    com.veteroch4k.tasktraker: DEBUG
