spring:
  application:
    name: task-time-traker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/task_tracker?stringtype=unspecified
    username: root
    password: root

  sql:
    init:
      mode: never

  liquibase:
    change-log: classpath:/db/changelog/db.migrations-master.yaml
    enabled: true

jwt:
  secret:
    access: 7YD+r7kLLg6v+f69GAUto0bh0JeYavEcJbk8qyrUBhLf0bp5vATCPsTE/XoH+vOKf1zYfobNH41zbgdl+kI8oQ==
    refresh: GMOFSSwnQb18+GwWj/tbAp0KKZ963Cn4IV7zmdFkcDCaBQKnHXP3rADKHCQUNzNBFIIACfgZLuE3jYNmpsfeyg==


mybatis:
  type-aliases-package: com.veteroch4k.tasktracker.models

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true


server:
  port: 8080
logging:
  level:
    root: info
    com.veteroch4k.tasktraker: DEBUG
